### ISSUE TITLE
CloudFormation Deployment Failure: LogGroup Resource Conflict and ECR Repository Naming Issues

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/CFNDeployment#11]
# CloudFormation Deployment Failure Analysis

## Summary
The CloudFormation deployment failed due to two main issues:
1. A resource conflict with an existing AWS::Logs::LogGroup
2. Inconsistent ECR repository naming in the infrastructure template

### Issue 1: AWS Logs LogGroup Already Exists

**Confidence Level:** 95%

**Impacted File:** `cloudformation-templates/infrastructure.yml`

**Problem:**
The CloudFormation deployment failed because the AWS::Logs::LogGroup resource named "cfndeployment-log-group" already exists in the AWS account. This resource was added in a recent commit but was not properly handled for idempotent deployments. When CloudFormation tried to create this log group, it failed with an "AlreadyExists" error, which triggered a rollback of the entire stack.

**Code Snippet:**
```yaml
AppLogGroup:
  Type: AWS::Logs::LogGroup
  Properties:
    LogGroupName: "cfndeployment-log-group"
    RetentionInDays: 14
```

**Error Log:**
```
Resource handler returned message: "Resource of type 'AWS::Logs::LogGroup' with identifier '{"/properties/LogGroupName":"cfndeployment-log-group"}' already exists." (RequestToken: 34d4fe5b-3fc0-5ef1-a357-48740bb4c641, HandlerErrorCode: AlreadyExists)
```

### Issue 2: ECR Repository Name Conflict

**Confidence Level:** 95%

**Impacted File:** `cloudformation-templates/infrastructure.yml`

**Problem:**
There is a resource name conflict in the CloudFormation template where two ECR repositories are defined with potentially the same name. In the most recent commit, the ImageRepository resource was changed to use "reponame2" while ImageRepository2 still uses "reponame". This creates confusion in the deployment workflow which expects to use "reponame" for the web application deployment.

**Code Snippet:**
```yaml
ImageRepository:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: reponame2

ImageRepository2:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: reponame
```

**Error Log:**
```
The following resource(s) failed to create: [PublicLoadBalancerSG, ImageRepository, ContainerSecurityGroup, DummyTargetGroupPublic, ECSCluster, AppLogGroup]. Rollback requested by user.
```

### For Issue 1: AWS Logs LogGroup Already Exists

1. Modify the CloudFormation template to handle existing log groups by using the DeletionPolicy and UpdateReplacePolicy attributes:

```yaml
AppLogGroup:
  Type: AWS::Logs::LogGroup
  DeletionPolicy: Retain
  UpdateReplacePolicy: Retain
  Properties:
    LogGroupName: "cfndeployment-log-group"
    RetentionInDays: 14
```

2. Alternatively, use a dynamic name for the log group to avoid conflicts:

```yaml
AppLogGroup:
  Type: AWS::Logs::LogGroup
  Properties:
    LogGroupName: !Sub "${EnvironmentName}-log-group"
    RetentionInDays: 14
```

3. Another option is to use CloudFormation's Condition to check if the log group exists before attempting to create it:

```yaml
Conditions:
  CreateLogGroup: !Equals [!Ref ShouldCreateLogGroup, true]

Parameters:
  ShouldCreateLogGroup:
    Type: String
    Default: "false"
    AllowedValues: ["true", "false"]

Resources:
  AppLogGroup:
    Type: AWS::Logs::LogGroup
    Condition: CreateLogGroup
    Properties:
      LogGroupName: "cfndeployment-log-group"
      RetentionInDays: 14
```

### For Issue 2: ECR Repository Name Conflict

1. Ensure that the ECR repository names are consistent with the workflow requirements:

```yaml
ImageRepository:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: !Sub "${EnvironmentName}-primary-repo"

ImageRepository2:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: !Sub "${EnvironmentName}-secondary-repo"
```

2. Update the workflow file (.github/workflows/deploy.yml) to use the correct repository name:

```yaml
- name: Build, tag, and push webapp image
  id: build-image
  env:
    ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
    ECR_REPOSITORY: !Sub "${EnvironmentName}-primary-repo"
    IMAGE_TAG: webapp-${{ github.sha }}
  run: |
    docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
    docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> "$GITHUB_OUTPUT"
```

3. Consider using CloudFormation outputs to export the repository names and reference them in the workflow to ensure consistency.
