### ISSUE TITLE
CloudFormation Deployment Failure: Stack in ROLLBACK_FAILED state and ECR Repository Name Mismatch

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/CFNDeployment#12]
### Issue 1: CloudFormation Stack in ROLLBACK_FAILED State

**Confidence Level:** 90%

#### Analysis
The CloudFormation stack is in a ROLLBACK_FAILED state due to an EC2Instance resource that failed to receive the required signal within the specified duration. However, there is no EC2Instance resource defined in the current CloudFormation templates. This indicates that there was a previous deployment with an EC2Instance resource that failed, and the stack is now in a state that prevents updates.

#### Impacted File
`.github/workflows/deploy.yml`

#### Code Snippet
```yaml
- name: Deploy infrastructure with CloudFormation
  id: infrastructure-stack
  uses: aws-actions/aws-cloudformation-github-deploy@v1
  with:
    name: ${{ steps.env-name.outputs.environment }}-infra
    template: cloudformation-templates/infrastructure.yml
    role-arn: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-cloudformation-stack-role
    no-fail-on-empty-changeset: "1"
    parameter-overrides: >-
      EnvironmentName=${{ steps.env-name.outputs.environment }},
      VPC=${{ steps.vpc.outputs.vpc-id }},
      PublicSubnetOne=${{ steps.vpc.outputs.subnet-one }},
      PublicSubnetTwo=${{ steps.vpc.outputs.subnet-two }}
```

#### Error Log
```
##[error]Stack:arn:aws:cloudformation:us-east-2:***:stack/CloudSmith-Delivery-Troubleshooting-CFNDeployment-infra/45982dd0-4e1b-11f0-9cff-02499d1c9c23 is in ROLLBACK_FAILED state and can not be updated.

Failed Resources from Current Deployment:
|  2025-06-20T21:12:56.928000+00:00|  EC2Instance        |  AWS::EC2::Instance                         |  Failed to receive 1 resource signal(s) within the specified duration  |
```

#### Solution Plan
1. Delete the existing CloudFormation stack that is in ROLLBACK_FAILED state
2. Modify the GitHub workflow to handle this situation by adding a step to check if the stack exists and is in a failed state before attempting deployment
3. If the stack is in a failed state, delete it before attempting to create it again
4. Add proper error handling and retry mechanisms

Here's the code change needed for the workflow file:

```yaml
- name: Check if stack exists and is in failed state
  id: check-stack
  run: |
    STACK_NAME="${{ steps.env-name.outputs.environment }}-infra"
    STACK_STATUS=$(aws cloudformation describe-stacks --stack-name "$STACK_NAME" --query "Stacks[0].StackStatus" --output text 2>/dev/null || echo "STACK_NOT_FOUND")
    echo "stack_status=$STACK_STATUS" >> "$GITHUB_OUTPUT"
    if [[ "$STACK_STATUS" == *FAILED* || "$STACK_STATUS" == *ROLLBACK* ]]; then
      echo "Stack is in a failed state, deleting it..."
      aws cloudformation delete-stack --stack-name "$STACK_NAME"
      echo "Waiting for stack deletion to complete..."
      aws cloudformation wait stack-delete-complete --stack-name "$STACK_NAME"
      echo "Stack deleted successfully"
    fi

- name: Deploy infrastructure with CloudFormation
  id: infrastructure-stack
  uses: aws-actions/aws-cloudformation-github-deploy@v1
  with:
    name: ${{ steps.env-name.outputs.environment }}-infra
    template: cloudformation-templates/infrastructure.yml
    role-arn: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-cloudformation-stack-role
    no-fail-on-empty-changeset: "1"
    parameter-overrides: >-
      EnvironmentName=${{ steps.env-name.outputs.environment }},
      VPC=${{ steps.vpc.outputs.vpc-id }},
      PublicSubnetOne=${{ steps.vpc.outputs.subnet-one }},
      PublicSubnetTwo=${{ steps.vpc.outputs.subnet-two }}
```

### Issue 2: ECR Repository Name Mismatch

**Confidence Level:** 90%

#### Analysis
There is a mismatch between the ECR repository name in the infrastructure.yml template ("reponame1") and the repository name used in the deploy-web-app job ("reponame"), which would cause the image push to fail if the infrastructure deployment were successful.

#### Impacted File
`cloudformation-templates/infrastructure.yml`

#### Code Snippet
```yaml
# ECR Repository
ImageRepository:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: reponame1
```

#### Error Log
The repository name mismatch would cause an error when trying to push the Docker image in the deploy-web-app job:
```yaml
- name: Build, tag, and push webapp image
  id: build-image
  env:
    ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
    ECR_REPOSITORY: reponame
    IMAGE_TAG: webapp-${{ github.sha }}
```

#### Solution Plan
1. Ensure the ECR repository name is consistent between the infrastructure template and the workflow
2. Update either the infrastructure.yml file or the workflow file to use the same repository name

Option 1 - Update infrastructure.yml:
```yaml
# ECR Repository
ImageRepository:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: reponame
```

Option 2 - Update the workflow file:
```yaml
- name: Build, tag, and push webapp image
  id: build-image
  env:
    ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
    ECR_REPOSITORY: reponame1
    IMAGE_TAG: webapp-${{ github.sha }}
```
