### ISSUE TITLE
CloudFormation Deployment Timeout: EC2 Instance CreationPolicy Too Short

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/CFNDeployment#14]
## Root Cause Analysis

**Confidence Level:** 90%

### Problem Description

The CloudFormation deployment was cancelled due to a timeout in the EC2 instance creation. The EC2 instance has an extremely short timeout of only 10 seconds (PT10S) in its CreationPolicy ResourceSignal configuration, which is insufficient for the instance to boot up and send the required signal.

### Impacted File
`cloudformation-templates/infrastructure.yml`

### Problematic Code
```yaml
EC2Instance:
  Type: AWS::EC2::Instance
  Properties:
    InstanceType: t2.micro
    SubnetId: !Ref PublicSubnetOne
    SecurityGroupIds:
      - !Ref ContainerSecurityGroup
    ImageId: ami-0c55b159cbfafe1f0  # Amazon Linux 2 AMI (adjust for your region)
    Tags:
      - Key: Name
        Value: !Sub "${EnvironmentName}-test-instance"
  CreationPolicy:
    ResourceSignal:
      Timeout: PT10S
```

### Error Log
```
2025-06-20T21:00:14.1328696Z ##[error]The operation was canceled.
```

## Solution Plan

1. Increase the timeout value in the EC2 instance's CreationPolicy to allow sufficient time for the instance to boot up and send the signal.
2. A typical EC2 instance needs at least several minutes to fully initialize, so a timeout of 5-15 minutes would be more appropriate.
3. Modify the infrastructure.yml file as follows:

```yaml
EC2Instance:
  Type: AWS::EC2::Instance
  Properties:
    InstanceType: t2.micro
    SubnetId: !Ref PublicSubnetOne
    SecurityGroupIds:
      - !Ref ContainerSecurityGroup
    ImageId: ami-0c55b159cbfafe1f0  # Amazon Linux 2 AMI (adjust for your region)
    Tags:
      - Key: Name
        Value: !Sub "${EnvironmentName}-test-instance"
  CreationPolicy:
    ResourceSignal:
      Timeout: PT15M
```

This change increases the timeout from 10 seconds to 15 minutes, which should be sufficient for the EC2 instance to boot up and send the required signal. Alternatively, if the instance doesn't need to send a signal, you could remove the CreationPolicy entirely.
