### ISSUE TITLE
CloudFormation Deployment Failure: Invalid ECR Repository Name

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/CFNDeployment#17]
# CloudFormation Deployment Failure: Invalid ECR Repository Name

## Issue Summary
The CloudFormation deployment is failing because the ECR repository name "repositoryName" in the infrastructure.yml template does not meet AWS ECR repository naming requirements.

## Root Cause Analysis
**Confidence Level: 95%**

The CloudFormation deployment failed because the ECR repository name "repositoryName" in the infrastructure.yml template does not meet AWS ECR repository naming requirements. ECR repository names must follow a specific pattern, typically allowing lowercase letters, numbers, hyphens, and underscores, but not generic placeholder names like "repositoryName".

The error message "Model validation failed (#/RepositoryName: failed validation constraint for keyword [pattern])" indicates that the repository name does not match the required pattern for ECR repositories.

### Impacted File
`cloudformation-templates/infrastructure.yml`

### Problematic Code
```yaml
# ECR Repository
ImageRepository:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: repositoryName
```

### Error Log
```
Resource handler returned message: "Model validation failed (#/RepositoryName: failed validation constraint for keyword [pattern])" (RequestToken: d8473b46-45b2-3e7f-e5e3-bc31f23c332e, HandlerErrorCode: InvalidRequest)
```

## Solution Plan
1. Update the ECR repository name in the CloudFormation template to follow AWS ECR naming requirements
2. Use a valid name that follows the pattern: lowercase letters, numbers, hyphens, and underscores
3. Consider using a dynamic name based on the environment name or a more specific name related to the application
4. Replace the static "repositoryName" with a more appropriate name

### Recommended Fix
```yaml
# ECR Repository
ImageRepository:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: !Sub ${EnvironmentName}-app-repo
```

This uses the CloudFormation !Sub function to create a repository name based on the environment name parameter, which will generate a valid name like "CloudSmith-Delivery-Troubleshooting-CFNDeployment-app-repo".
