### ISSUE TITLE
CloudFormation Deployment Failure: Log Group Resource Already Exists

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/CFNDeployment#19]
# CloudFormation Deployment Failure: Log Group Resource Already Exists

## Issue Summary
The CloudFormation deployment is failing because the AWS::Logs::LogGroup resource named "cfndeployment-log-group" already exists in the AWS account. CloudFormation cannot create a resource with the same name as an existing resource.

## Root Cause Analysis
**Confidence Level: 95%**

The CloudFormation deployment failed because the AWS::Logs::LogGroup resource named "cfndeployment-log-group" already exists in the AWS account. CloudFormation cannot create a resource with the same name as an existing resource. This is causing the entire stack creation to fail and roll back.

### Impacted File
`cloudformation-templates/infrastructure.yml`

### Problematic Code
```yaml
  AppLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: "cfndeployment-log-group"
      RetentionInDays: 14
```

### Error Log
```
Resource handler returned message: "Resource of type 'AWS::Logs::LogGroup' with identifier '{"/properties/LogGroupName":"cfndeployment-log-group"}' already exists." (RequestToken: 34d4fe5b-3fc0-5ef1-a357-48740bb4c641, HandlerErrorCode: AlreadyExists)
```

## Solution Plan
1. Make the LogGroupName unique by incorporating the environment name or a timestamp into it
2. Update the CloudFormation template to use a dynamic LogGroupName that won't conflict with existing resources
3. Replace the hardcoded LogGroupName with a parameterized value that includes the environment name

### Recommended Fix
```yaml
  AppLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "${EnvironmentName}-log-group"
      RetentionInDays: 14
```

This change uses CloudFormation's `!Sub` function to create a unique log group name based on the environment name parameter, which will avoid conflicts with existing resources.
