### ISSUE TITLE
CloudFormation Deployment Failure: Invalid ECR Repository Name Pattern

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/CFNDeployment#21]
## Root Cause Analysis

**Confidence Level:** 95%

### Finding

**Analysis:**
The CloudFormation deployment failed because the ECR repository name "repositoryName" in the infrastructure template does not meet AWS ECR repository naming requirements. ECR repository names must follow a specific pattern, and the static value "repositoryName" fails the pattern validation.

**Impacted File:**
`cloudformation-templates/infrastructure.yml`

**Problematic Code:**
```yaml
# ECR Repository
ImageRepository:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: repositoryName
```

**Error Log:**
```
Resource handler returned message: "Model validation failed (#/RepositoryName: failed validation constraint for keyword [pattern])" (RequestToken: d8473b46-45b2-3e7f-e5e3-bc31f23c332e, HandlerErrorCode: InvalidRequest)
```

## Solution Plan

1. Replace the static repository name with a dynamic name based on the environment name parameter.
2. Ensure the repository name follows AWS ECR naming requirements (lowercase letters, numbers, hyphens, underscores, and periods).
3. Update the CloudFormation template with the corrected repository name.

**Corrected code:**
```yaml
# ECR Repository
ImageRepository:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: !Sub ${EnvironmentName}-repository
```

4. This change uses CloudFormation's !Sub function to create a dynamic repository name based on the environment name parameter.
5. Deploy the updated CloudFormation template.
6. Update the ECR_REPOSITORY value in the workflow file to match the new repository name pattern.
