### ISSUE TITLE
CloudFormation Deployment Timeout: EC2 Instance Creation Policy Too Short

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/CFNDeployment#22]
## Root Cause Analysis

**Confidence Level:** 95%

### Finding

**Analysis:**
The CloudFormation deployment was cancelled due to an EC2 instance creation timeout. The EC2Instance resource in the infrastructure.yml template has a CreationPolicy with a very short timeout of only 10 seconds (PT10S), which is insufficient for an EC2 instance to initialize and send a success signal.

**Impacted File:**
`cloudformation-templates/infrastructure.yml`

**Problematic Code:**
```yaml
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SubnetId: !Ref PublicSubnetOne
      SecurityGroupIds:
        - !Ref ContainerSecurityGroup
      ImageId: ami-0c55b159cbfafe1f0  # Amazon Linux 2 AMI (adjust for your region)
      Tags:
        - Key: Name
          Value: !Sub "${EnvironmentName}-test-instance"
    CreationPolicy:
      ResourceSignal:
        Timeout: PT10S
```

**Error Log:**
```
##[error]The operation was canceled.
```

## Solution Plan

1. Increase the EC2 instance CreationPolicy timeout to a more reasonable value.
2. Modify the CloudFormation template to allow sufficient time for the EC2 instance to initialize.
3. Update the infrastructure.yml file with the corrected timeout value.

**Corrected code:**
```yaml
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SubnetId: !Ref PublicSubnetOne
      SecurityGroupIds:
        - !Ref ContainerSecurityGroup
      ImageId: ami-0c55b159cbfafe1f0  # Amazon Linux 2 AMI (adjust for your region)
      Tags:
        - Key: Name
          Value: !Sub "${EnvironmentName}-test-instance"
    CreationPolicy:
      ResourceSignal:
        Timeout: PT15M
```

4. The timeout value PT15M (15 minutes) provides sufficient time for the EC2 instance to initialize and send a success signal.
5. Alternatively, if the EC2 instance doesn't need to send a signal, you can remove the CreationPolicy entirely.
6. Deploy the updated CloudFormation template.
