### ISSUE TITLE
CloudFormation Deployment Failure: Log Group Resource Already Exists

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/CFNDeployment#23]
## Root Cause Analysis

**Confidence Level:** 95%

### Finding

**Analysis:**
The CloudFormation deployment failed because the AWS::Logs::LogGroup resource named "AppLogGroup" with LogGroupName "cfndeployment-log-group" already exists in AWS. The error message "Resource of type 'AWS::Logs::LogGroup' with identifier '{"/properties/LogGroupName":"cfndeployment-log-group"}' already exists" indicates a resource conflict where CloudFormation is trying to create a resource that already exists in the AWS account.

**Impacted File:**
`cloudformation-templates/infrastructure.yml`

**Problematic Code:**
```yaml
  AppLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: "cfndeployment-log-group"
      RetentionInDays: 14
```

**Error Log:**
```
Resource handler returned message: "Resource of type 'AWS::Logs::LogGroup' with identifier '{"/properties/LogGroupName":"cfndeployment-log-group"}' already exists." (RequestToken: 34d4fe5b-3fc0-5ef1-a357-48740bb4c641, HandlerErrorCode: AlreadyExists)
```

## Solution Plan

1. Modify the CloudFormation template to use a unique LogGroupName for each deployment.
2. Use the environment name as part of the LogGroupName to ensure uniqueness.
3. Update the infrastructure.yml file with the corrected LogGroupName.

**Corrected code:**
```yaml
  AppLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "${EnvironmentName}-log-group"
      RetentionInDays: 14
```

4. This change uses CloudFormation's !Sub function to create a dynamic log group name based on the environment name parameter.
5. Deploy the updated CloudFormation template.
6. If you need to keep using the same log group across deployments, consider using DeletionPolicy: Retain and updating the template to import the existing resource instead of creating it.
