### ISSUE TITLE
CloudFormation Deployment Failure: Invalid ECR Repository Name

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/CFNDeployment#25]
# CloudFormation Deployment Failure: Invalid ECR Repository Name

## Problem Description
The CloudFormation stack deployment is failing because the ECR repository name "repositoryName" is invalid. AWS ECR repository names must follow specific naming patterns, and the literal string "repositoryName" does not meet the validation requirements.

## Root Cause Analysis
- **Confidence Level**: 95%
- **Impacted File**: `cloudformation-templates/infrastructure.yml`
- **Error Message**: `"Resource handler returned message: \"Model validation failed (#/RepositoryName: failed validation constraint for keyword [pattern])\""` 

### Problematic Code
```yaml
# ECR Repository
ImageRepository:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: repositoryName
```

## Solution Plan
1. Update the ECR repository name in the CloudFormation template to follow AWS naming requirements
2. Replace the generic "repositoryName" with a valid name that includes the environment name for uniqueness
3. Modify the infrastructure.yml file to use a dynamic name based on the environment parameter
4. Update the workflow file to reference the correct repository name

### Recommended Changes

**In cloudformation-templates/infrastructure.yml:**
```yaml
# ECR Repository
ImageRepository:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: !Sub ${EnvironmentName}-app-repo
```

**In .github/workflows/deploy.yml (deploy-web-app job):**
```yaml
- name: Build, tag, and push webapp image
  id: build-image
  env:
    ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
    ECR_REPOSITORY: ${{ needs.deploy-infrastructure.outputs.env-name }}-app-repo
    IMAGE_TAG: webapp-${{ github.sha }}
  run: |
    docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
    docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> "$GITHUB_OUTPUT"
```

This ensures the repository name is unique per environment and follows AWS naming conventions.
