### ISSUE TITLE
CloudFormation Deployment Failure: CloudWatch Logs Group Name Conflict

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/CFNDeployment#27]
# CloudFormation Deployment Failure: CloudWatch Logs Group Name Conflict

## Problem Description
The CloudFormation deployment is failing because it's attempting to create a CloudWatch Logs log group with the name "cfndeployment-log-group" that already exists. AWS CloudWatch Logs log group names must be unique within an AWS account, and this log group was likely created by a previous deployment. The error triggered a rollback of the entire stack, causing all other resources to be cancelled during creation.

## Root Cause Analysis
- **Confidence Level**: 95%
- **Impacted File**: `cloudformation-templates/infrastructure.yml`
- **Error Message**: `Resource handler returned message: "Resource of type 'AWS::Logs::LogGroup' with identifier '{"/properties/LogGroupName":"cfndeployment-log-group"}' already exists."`

### Problematic Code
```yaml
AppLogGroup:
  Type: AWS::Logs::LogGroup
  Properties:
    LogGroupName: "cfndeployment-log-group"
    RetentionInDays: 14
```

## Solution Plan
1. Modify the CloudFormation template to use a dynamic log group name that includes the environment name or stack name to ensure uniqueness
2. Add a DeletionPolicy: Retain attribute if you want to keep logs across deployments
3. Consider using !Sub function to create a parameterized name

### Recommended Changes

```yaml
AppLogGroup:
  Type: AWS::Logs::LogGroup
  Properties:
    LogGroupName: !Sub "${EnvironmentName}-log-group"
    RetentionInDays: 14
  DeletionPolicy: Retain
```

This ensures each environment gets its own log group and prevents name conflicts between deployments. The DeletionPolicy: Retain attribute ensures logs are preserved even if the stack is deleted.
