### ISSUE TITLE
Fix EC2 instance creation timeout in CloudFormation template

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/CFNDeployment#30]
## Troubleshooting
After analyzing the workflow run logs and the source code, I've identified the following findings and the appropriate solution plan:

### 1. The CloudFormation deployment was cancelled due to an EC2 instance creation timeout. The EC2Instance resource in the CloudFormation template has a very short CreationPolicy timeout of only 10 seconds (PT10S), which is insufficient for an EC2 instance to initialize and signal completion. This is causing the CloudFormation stack to wait for the signal, timeout after 10 seconds, and then roll back.
The CloudFormation template has an unrealistic timeout value for EC2 instance creation.

### Finding 1: The CloudFormation deployment was cancelled due to an EC2 instance creation timeout. The EC2Instance resource in the CloudFormation template has a very short CreationPolicy timeout of only 10 seconds (PT10S), which is insufficient for an EC2 instance to initialize and signal completion. This is causing the CloudFormation stack to wait for the signal, timeout after 10 seconds, and then roll back.
**Error Log:**

2025-06-20T21:00:14.1328696Z ##[error]The operation was canceled.

**Problematic Code:**

# EC2 Instance with short timeout
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SubnetId: !Ref PublicSubnetOne
      SecurityGroupIds:
        - !Ref ContainerSecurityGroup
      ImageId: ami-0c55b159cbfafe1f0  # Amazon Linux 2 AMI (adjust for your region)
      Tags:
        - Key: Name
          Value: !Sub "${EnvironmentName}-test-instance"
    CreationPolicy:
      ResourceSignal:
        Timeout: PT10S

**Impacted File:** `cloudformation-templates/infrastructure.yml`

### Step 1: Increase the EC2 instance CreationPolicy timeout to a more reasonable value.
The timeout needs to be increased to allow sufficient time for instance initialization.

### Step 2: EC2 instances typically need several minutes to initialize, so a timeout of at least 5-15 minutes is recommended.
EC2 instances require more time than the current 10 seconds setting.

### Step 3: Update the CloudFormation template with the following changes:

```yaml
# EC2 Instance with appropriate timeout
EC2Instance:
  Type: AWS::EC2::Instance
  Properties:
    InstanceType: t2.micro
    SubnetId: !Ref PublicSubnetOne
    SecurityGroupIds:
      - !Ref ContainerSecurityGroup
    ImageId: ami-0c55b159cbfafe1f0  # Amazon Linux 2 AMI (adjust for your region)
    Tags:
      - Key: Name
        Value: !Sub "${EnvironmentName}-test-instance"
  CreationPolicy:
    ResourceSignal:
      Timeout: PT15M
```

This increases the timeout from 10 seconds to 15 minutes, giving the EC2 instance sufficient time to initialize and send the required signal. Alternatively, if the EC2 instance is not configured to send a success signal, you could remove the CreationPolicy entirely.

---

*Confidence level: 95%*
