### ISSUE TITLE
CloudFormation Deployment Failure: EC2 Instance Creation Timeout and IAM Permission Issues

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/CFNDeployment#37]
# Troubleshooting Analysis

## Summary
The CloudFormation deployment is failing due to two critical issues:

1. **EC2 Instance Creation Timeout**: The EC2 instance creation policy has an extremely short timeout (10 seconds) which is insufficient for initialization and signaling.
2. **IAM Permission Issue**: The CloudFormation service role lacks the necessary EC2 termination permissions required during stack rollback.

## Confidence Level
**95%**

#### Analysis
The EC2 instance creation failed because the CreationPolicy has an extremely short timeout (PT10S = 10 seconds) which is insufficient for the EC2 instance to initialize and send the required signal back to CloudFormation.

#### Impacted File
`cloudformation-templates/infrastructure.yml`

#### Problematic Code
```yaml
EC2Instance:
  Type: AWS::EC2::Instance
  Properties:
    InstanceType: t2.micro
    SubnetId: !Ref PublicSubnetOne
    SecurityGroupIds:
      - !Ref ContainerSecurityGroup
    ImageId: ami-0c55b159cbfafe1f0  # Amazon Linux 2 AMI (adjust for your region)
    Tags:
      - Key: Name
        Value: !Sub "${EnvironmentName}-test-instance"
  CreationPolicy:
    ResourceSignal:
      Timeout: PT10S
```

#### Error Log
```
EC2Instance-CREATE_FAILED-2025-06-20T21:12:56.928Z | EC2Instance | AWS::EC2::Instance | Failed to receive 1 resource signal(s) within the specified duration
```

#### Solution Plan
1. Modify the CreationPolicy timeout in the CloudFormation template to allow sufficient time for the EC2 instance to initialize and send the signal.
2. Open the file at cloudformation-templates/infrastructure.yml
3. Locate the EC2Instance resource definition
4. Change the CreationPolicy timeout from PT10S to a more reasonable value like PT5M (5 minutes)
5. The modified code should look like:

```yaml
EC2Instance:
  Type: AWS::EC2::Instance
  Properties:
    InstanceType: t2.micro
    SubnetId: !Ref PublicSubnetOne
    SecurityGroupIds:
      - !Ref ContainerSecurityGroup
    ImageId: ami-0c55b159cbfafe1f0  # Amazon Linux 2 AMI (adjust for your region)
    Tags:
      - Key: Name
        Value: !Sub "${EnvironmentName}-test-instance"
  CreationPolicy:
    ResourceSignal:
      Timeout: PT5M
```

6. Save the file and commit the changes
7. Push the changes to the repository to trigger the workflow again

#### Analysis
The CloudFormation stack rollback failed because the IAM role used for deployment (github-actions-cloudformation-stack-role) lacks the necessary ec2:TerminateInstances permission required to clean up resources during rollback.

#### Impacted File
`.github/workflows/deploy.yml`

#### Problematic Code
```yaml
- name: Deploy infrastructure with CloudFormation
  id: infrastructure-stack
  uses: aws-actions/aws-cloudformation-github-deploy@v1
  with:
    name: ${{ steps.env-name.outputs.environment }}-infra
    template: cloudformation-templates/infrastructure.yml
    role-arn: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-cloudformation-stack-role
    no-fail-on-empty-changeset: "1"
    parameter-overrides: >-
      EnvironmentName=${{ steps.env-name.outputs.environment }},
      VPC=${{ steps.vpc.outputs.vpc-id }},
      PublicSubnetOne=${{ steps.vpc.outputs.subnet-one }},
      PublicSubnetTwo=${{ steps.vpc.outputs.subnet-two }}
```

#### Error Log
```
EC2Instance-DELETE_FAILED-2025-06-20T21:13:00.485Z | EC2Instance | AWS::EC2::Instance | Resource handler returned message: "You are not authorized to perform this operation. User: arn:aws:sts::388276022184:assumed-role/github-actions-cloudformation-stack-role/AWSCloudFormation is not authorized to perform: ec2:TerminateInstances on resource: arn:aws:ec2:us-east-2:388276022184:instance/i-0f845ac99ac4ba304 because no identity-based policy allows the ec2:TerminateInstances action. (Service: Ec2, Status Code: 403, Request ID: 3fd0e032-a227-4377-8ccf-f21ead4dc832) (SDK Attempt Count: 1)" (RequestToken: 1207ed42-3c50-c1a7-92d0-f93e1d8b5d06, HandlerErrorCode: AccessDenied)
```

#### Solution Plan
1. Update the IAM role permissions for the CloudFormation service role to include the necessary EC2 termination permissions
2. Log in to the AWS Management Console
3. Navigate to the IAM service
4. Find and select the role "github-actions-cloudformation-stack-role"
5. Add a new inline policy or update an existing policy to include the following permissions:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "ec2:TerminateInstances",
                "ec2:DeleteSecurityGroup",
                "ec2:DescribeInstances",
                "ec2:DescribeSecurityGroups"
            ],
            "Resource": "*"
        }
    ]
}
```

6. Save the updated policy
7. If there are any stuck resources from previous failed deployments, manually clean them up in the AWS Console
8. Re-run the GitHub Actions workflow after making both this change and the timeout change
