### ISSUE TITLE
CloudFormation Stack Deployment Failure: EC2Instance CreationPolicy Timeout Too Short

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/CFNDeployment#4]
# Root Cause Analysis: CloudFormation Stack Deployment Failure

## Summary
The CloudFormation deployment is failing because it's trying to update a stack that is currently in the `DELETE_IN_PROGRESS` state. This is caused by the EC2Instance resource that was added with an extremely short CreationPolicy timeout (PT10S or 10 seconds), which is likely causing the stack to fail during creation and automatically roll back (delete). When the workflow tries to update the stack, it finds the stack in a DELETE_IN_PROGRESS state and fails.

## Affected Resources
- **File Path**: `cloudformation-templates/infrastructure.yml`
- **Resource**: EC2Instance

## Error Details
```
##[error]Stack:arn:aws:cloudformation:us-east-2:***:stack/CloudSmith-Delivery-Troubleshooting-CFNDeployment-infra/86f9c470-4e19-11f0-9555-0ad224689599 is in DELETE_IN_PROGRESS state and can not be updated.
```

## Problematic Code
```yaml
EC2Instance:
  Type: AWS::EC2::Instance
  Properties:
    InstanceType: t2.micro
    SubnetId: !Ref PublicSubnetOne
    SecurityGroupIds:
      - !Ref ContainerSecurityGroup
    ImageId: ami-0c55b159cbfafe1f0  # Amazon Linux 2 AMI (adjust for your region)
    Tags:
      - Key: Name
        Value: !Sub "${EnvironmentName}-test-instance"
  CreationPolicy:
    ResourceSignal:
      Timeout: PT10S
```

## Root Cause
The EC2 instance has a CreationPolicy with a timeout of only 10 seconds (PT10S). This is an extremely short time for an EC2 instance to boot up and send a success signal back to CloudFormation. When the instance fails to signal within this short timeframe, CloudFormation considers the stack creation failed and automatically initiates a rollback (deletion). When the GitHub workflow tries to update the stack, it encounters the stack in a DELETE_IN_PROGRESS state, which causes the deployment to fail.

## Solution Plan
1. Wait for the current stack deletion to complete (this happens automatically when a stack creation fails)
2. Increase the CreationPolicy timeout to a more reasonable value (e.g., PT5M for 5 minutes) to give the EC2 instance enough time to signal completion
3. Alternatively, remove the CreationPolicy entirely if the EC2 instance doesn't need to signal completion
4. If the EC2 instance is expected to signal completion, ensure the instance has the proper IAM permissions and user data script to send the signal

## Recommended Code Changes
```yaml
EC2Instance:
  Type: AWS::EC2::Instance
  Properties:
    InstanceType: t2.micro
    SubnetId: !Ref PublicSubnetOne
    SecurityGroupIds:
      - !Ref ContainerSecurityGroup
    ImageId: ami-0c55b159cbfafe1f0  # Amazon Linux 2 AMI (adjust for your region)
    Tags:
      - Key: Name
        Value: !Sub "${EnvironmentName}-test-instance"
  CreationPolicy:
    ResourceSignal:
      Timeout: PT5M
```

## Confidence Level
95% - The error message clearly indicates the stack is in DELETE_IN_PROGRESS state, and the EC2 instance with a very short CreationPolicy timeout is the most likely cause of the initial failure that triggered the deletion.
