### ISSUE TITLE
CloudFormation Deployment Failure: EC2 Instance Creation Timeout and IAM Permission Issues

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/CFNDeployment#42]
## Troubleshooting Report

After reviewing the workflow run logs and examining the source code, I have identified the following findings along with a suitable solution plan.

### Trigger details

| Workflow run  | Branch  | Commit  |
|---|---|---|
| [15787719753](https://github.com/CloudSmith-Delivery-Troubleshooting/CFNDeployment/actions/runs/15787719753)  |  ```ec2-timeout``` |  ```8adcbcdb0732f43025d6714d83152205088e36e8``` |

----

### Issue 1: The EC2 instance creation failed because the CreationPolicy's ResourceSignal timeout is set too short (10 seconds), which is insufficient for the EC2 instance to initialize and send the required signal back to CloudFormation.

**Problem**: The EC2 instance creation failed because the CreationPolicy's ResourceSignal timeout is set too short (10 seconds), which is insufficient for the EC2 instance to initialize and send the required signal back to CloudFormation.

**File**: ```cloudformation-templates/infrastructure.yml```

**Error Log**:
```
EC2Instance-CREATE_FAILED-2025-06-20T21:12:56.928Z | AWS::EC2::Instance | Failed to receive 1 resource signal(s) within the specified duration
```

**Code snippet**:
```
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SubnetId: !Ref PublicSubnetOne
      SecurityGroupIds:
        - !Ref ContainerSecurityGroup
      ImageId: ami-0c55b159cbfafe1f0  # Amazon Linux 2 AMI (adjust for your region)
      Tags:
        - Key: Name
          Value: !Sub "${EnvironmentName}-test-instance"
    CreationPolicy:
      ResourceSignal:
        Timeout: PT10S
```

**Solution Plan**:

1. Modify the CreationPolicy timeout in the CloudFormation template to allow more time for the EC2 instance to initialize and send the signal.
2. Update the cloudformation-templates/infrastructure.yml file by changing the timeout from PT10S (10 seconds) to at least PT5M (5 minutes).
3. The corrected code should look like:

```yaml
EC2Instance:
  Type: AWS::EC2::Instance
  Properties:
    InstanceType: t2.micro
    SubnetId: !Ref PublicSubnetOne
    SecurityGroupIds:
      - !Ref ContainerSecurityGroup
    ImageId: ami-0c55b159cbfafe1f0  # Amazon Linux 2 AMI (adjust for your region)
    Tags:
      - Key: Name
        Value: !Sub "${EnvironmentName}-test-instance"
  CreationPolicy:
    ResourceSignal:
      Timeout: PT5M
```

4. Commit and push the changes to the repository.
5. Re-run the GitHub workflow to deploy the infrastructure with the updated timeout.

----

### Issue 2: The CloudFormation stack rollback failed because the IAM role used for deployment (github-actions-cloudformation-stack-role) lacks the necessary permissions to terminate EC2 instances, which is required during stack rollback.

**Problem**: The CloudFormation stack rollback failed because the IAM role used for deployment (github-actions-cloudformation-stack-role) lacks the necessary permissions to terminate EC2 instances, which is required during stack rollback.

**File**: ```N/A (IAM role permissions issue)```

**Error Log**:
```
EC2Instance-DELETE_FAILED-2025-06-20T21:13:00.485Z | AWS::EC2::Instance | Resource handler returned message: "You are not authorized to perform this operation. User: arn:aws:sts::388276022184:assumed-role/github-actions-cloudformation-stack-role/AWSCloudFormation is not authorized to perform: ec2:TerminateInstances on resource: arn:aws:ec2:us-east-2:388276022184:instance/i-0f845ac99ac4ba304 because no identity-based policy allows the ec2:TerminateInstances action. (Service: Ec2, Status Code: 403, Request ID: 3fd0e032-a227-4377-8ccf-f21ead4dc832) (SDK Attempt Count: 1)" (RequestToken: 1207ed42-3c50-c1a7-92d0-f93e1d8b5d06, HandlerErrorCode: AccessDenied)
```

**Code snippet**:
```
role-arn: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-cloudformation-stack-role
```

**Solution Plan**:

1. Update the IAM role permissions for the github-actions-cloudformation-stack-role to include EC2 termination permissions.
2. Log in to the AWS Management Console.
3. Navigate to the IAM service.
4. Find and select the role "github-actions-cloudformation-stack-role".
5. Add an inline policy or attach a managed policy that includes the following permissions:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "ec2:TerminateInstances",
                "ec2:DeleteSecurityGroup",
                "ec2:DescribeInstances",
                "ec2:DescribeInstanceStatus"
            ],
            "Resource": "*"
        }
    ]
}
```

6. Save the policy changes.
7. Clean up the failed CloudFormation stack manually:
   a. Log in to the AWS Management Console
   b. Navigate to the CloudFormation service
   c. Select the failed stack "CloudSmith-Delivery-Troubleshooting-CFNDeployment-infra"
   d. Delete the stack with the option to retain resources if needed
8. After fixing both issues (timeout and IAM permissions), re-run the GitHub workflow to deploy the infrastructure.

----

*Confidence level: 95%*

----

Generated by CloudSmith.
