### ISSUE TITLE
CloudFormation Deployment Failure: EC2 ResourceSignal Timeout and IAM Permission Issues

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/CFNDeployment#43]
### Trigger details

| Workflow run  | Branch  | Commit  |
|---|---|---|
| [Deploy workflow run #15787719753](https://github.com/CloudSmith-Delivery-Troubleshooting/CFNDeployment/actions/runs/15787719753)  |  ```ec2-timeout``` |  ```8adcbcdb0732f43025d6714d83152205088e36e8``` |

----

### Issue 1: The EC2 instance creation is failing because the CloudFormation template includes a ResourceSignal with a very short timeout (10 seconds) but the EC2 instance doesn't have any user data script to send the signal back to CloudFormation.

**Problem**: The EC2 instance creation is failing because the CloudFormation template includes a ResourceSignal with a very short timeout (10 seconds) but the EC2 instance doesn't have any user data script to send the signal back to CloudFormation.

**File**: ```cloudformation-templates/infrastructure.yml```

**Error Log**:
```
2025-06-20T21:12:56.928000+00:00|  EC2Instance        |  AWS::EC2::Instance                         |  Failed to receive 1 resource signal(s) within the specified duration
```

**Code snippet**:
```
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SubnetId: !Ref PublicSubnetOne
      SecurityGroupIds:
        - !Ref ContainerSecurityGroup
      ImageId: ami-0c55b159cbfafe1f0  # Amazon Linux 2 AMI (adjust for your region)
      Tags:
        - Key: Name
          Value: !Sub "${EnvironmentName}-test-instance"
    CreationPolicy:
      ResourceSignal:
        Timeout: PT10S
```

**Solution Plan**:

1. Either remove the CreationPolicy section from the EC2Instance resource if signals are not needed, or
2. Add a UserData script to the EC2 instance that sends a success signal back to CloudFormation, and increase the timeout to a more reasonable value.

Here's the corrected code:

Option 1 - Remove CreationPolicy:
```yaml
EC2Instance:
  Type: AWS::EC2::Instance
  Properties:
    InstanceType: t2.micro
    SubnetId: !Ref PublicSubnetOne
    SecurityGroupIds:
      - !Ref ContainerSecurityGroup
    ImageId: ami-0c55b159cbfafe1f0  # Amazon Linux 2 AMI (adjust for your region)
    Tags:
      - Key: Name
        Value: !Sub "${EnvironmentName}-test-instance"
```

Option 2 - Add UserData script and increase timeout:
```yaml
EC2Instance:
  Type: AWS::EC2::Instance
  Properties:
    InstanceType: t2.micro
    SubnetId: !Ref PublicSubnetOne
    SecurityGroupIds:
      - !Ref ContainerSecurityGroup
    ImageId: ami-0c55b159cbfafe1f0  # Amazon Linux 2 AMI (adjust for your region)
    Tags:
      - Key: Name
        Value: !Sub "${EnvironmentName}-test-instance"
    UserData:
      Fn::Base64: !Sub |
        #!/bin/bash -xe
        yum update -y
        yum install -y aws-cfn-bootstrap
        /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource EC2Instance --region ${AWS::Region}
  CreationPolicy:
    ResourceSignal:
      Timeout: PT5M
```

3. After making these changes, commit them to the repository and push to the ec2-timeout branch.
4. The GitHub Actions workflow will automatically trigger and deploy the updated CloudFormation template.

----

### Issue 2: The IAM role used for CloudFormation stack deployment lacks permissions to terminate EC2 instances, causing the stack to get stuck in ROLLBACK_FAILED state when cleanup is attempted.

**Problem**: The IAM role used for CloudFormation stack deployment lacks permissions to terminate EC2 instances, causing the stack to get stuck in ROLLBACK_FAILED state when cleanup is attempted.

**File**: ```N/A (IAM role configuration)```

**Error Log**:
```
Resource handler returned message: "You are not authorized to perform this operation. User: arn:aws:sts::388276022184:assumed-role/github-actions-cloudformation-stack-role/AWSCloudFormation is not authorized to perform: ec2:TerminateInstances on resource: arn:aws:ec2:us-east-2:388276022184:instance/i-0f845ac99ac4ba304 because no identity-based policy allows the ec2:TerminateInstances action. (Service: Ec2, Status Code: 403, Request ID: 3fd0e032-a227-4377-8ccf-f21ead4dc832) (SDK Attempt Count: 1)" (RequestToken: 1207ed42-3c50-c1a7-92d0-f93e1d8b5d06, HandlerErrorCode: AccessDenied)
```

**Code snippet**:
```
role-arn: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-cloudformation-stack-role
```

**Solution Plan**:

1. Update the IAM role permissions for the CloudFormation service role to include EC2 termination permissions:
   - Log into the AWS Management Console
   - Navigate to IAM > Roles
   - Find and select the role "github-actions-cloudformation-stack-role"
   - Add a new inline policy or update an existing policy to include the following permissions:
   ```json
   {
       "Version": "2012-10-17",
       "Statement": [
           {
               "Effect": "Allow",
               "Action": [
                   "ec2:TerminateInstances"
               ],
               "Resource": "*"
           }
       ]
   }
   ```
2. After updating the IAM role, manually delete the stuck CloudFormation stack:
   ```
   aws cloudformation delete-stack --stack-name CloudSmith-Delivery-Troubleshooting-CFNDeployment-infra
   ```
3. Once the stack is deleted, trigger the GitHub Actions workflow again to deploy with the updated CloudFormation template.

----

*Confidence level: 95%*

----

Generated by CloudSmith.
