### ISSUE TITLE
CloudFormation Deployment Failure: EC2 Instance Creation Timeout and IAM Permission Issue

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/CFNDeployment#45]
# CloudFormation Deployment Failure Analysis

## Summary
The CloudFormation deployment is failing due to two main issues:

1. **EC2 Instance Creation Timeout**: The EC2Instance resource has an extremely short timeout of 10 seconds (PT10S) in its CreationPolicy, which is insufficient for the EC2 instance to initialize and send the required signal back to CloudFormation.

2. **IAM Permission Issue**: The CloudFormation stack rollback failed because the IAM role used for deployment (github-actions-cloudformation-stack-role) does not have the necessary permissions to terminate EC2 instances during rollback operations.

## Workflow Details
- **Repository**: CloudSmith-Delivery-Troubleshooting/CFNDeployment
- **Workflow**: Deploy
- **Run ID**: 15787719753
- **Branch**: ec2-timeout
- **Commit**: 8adcbcdb0732f43025d6714d83152205088e36e8

### Problem
The CloudFormation template defines an EC2 instance with a CreationPolicy that has a timeout of only 10 seconds:

```yaml
EC2Instance:
  Type: AWS::EC2::Instance
  Properties:
    InstanceType: t2.micro
    SubnetId: !Ref PublicSubnetOne
    SecurityGroupIds:
      - !Ref ContainerSecurityGroup
    ImageId: ami-0c55b159cbfafe1f0  # Amazon Linux 2 AMI (adjust for your region)
    Tags:
      - Key: Name
        Value: !Sub "${EnvironmentName}-test-instance"
  CreationPolicy:
    ResourceSignal:
      Timeout: PT10S
```

### Error Log
```
2025-06-20T21:12:56.928000+00:00|  EC2Instance  |  AWS::EC2::Instance  |  Failed to receive 1 resource signal(s) within the specified duration
```

### Solution
1. Modify the CreationPolicy timeout in the CloudFormation template to allow more time for the EC2 instance to initialize and send the required signal.
2. Open the file `cloudformation-templates/infrastructure.yml`
3. Locate the EC2Instance resource definition
4. Change the CreationPolicy ResourceSignal Timeout from PT10S to a more reasonable value like PT5M (5 minutes)
5. The corrected code should look like:

```yaml
EC2Instance:
  Type: AWS::EC2::Instance
  Properties:
    InstanceType: t2.micro
    SubnetId: !Ref PublicSubnetOne
    SecurityGroupIds:
      - !Ref ContainerSecurityGroup
    ImageId: ami-0c55b159cbfafe1f0  # Amazon Linux 2 AMI (adjust for your region)
    Tags:
      - Key: Name
        Value: !Sub "${EnvironmentName}-test-instance"
  CreationPolicy:
    ResourceSignal:
      Timeout: PT5M
```

### Problem
The CloudFormation stack rollback failed because the IAM role used for deployment doesn't have the necessary permissions to terminate EC2 instances:

```yaml
- name: Deploy infrastructure with CloudFormation
  id: infrastructure-stack
  uses: aws-actions/aws-cloudformation-github-deploy@v1
  with:
    name: ${{ steps.env-name.outputs.environment }}-infra
    template: cloudformation-templates/infrastructure.yml
    role-arn: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-cloudformation-stack-role
    no-fail-on-empty-changeset: "1"
    parameter-overrides: >-
      EnvironmentName=${{ steps.env-name.outputs.environment }},
      VPC=${{ steps.vpc.outputs.vpc-id }},
      PublicSubnetOne=${{ steps.vpc.outputs.subnet-one }},
      PublicSubnetTwo=${{ steps.vpc.outputs.subnet-two }}
```

### Error Log
```
Resource handler returned message: "You are not authorized to perform this operation. User: arn:aws:sts::388276022184:assumed-role/github-actions-cloudformation-stack-role/AWSCloudFormation is not authorized to perform: ec2:TerminateInstances on resource: arn:aws:ec2:us-east-2:388276022184:instance/i-0f845ac99ac4ba304 because no identity-based policy allows the ec2:TerminateInstances action. (Service: Ec2, Status Code: 403, Request ID: 3fd0e032-a227-4377-8ccf-f21ead4dc832) (SDK Attempt Count: 1)" (RequestToken: 1207ed42-3c50-c1a7-92d0-f93e1d8b5d06, HandlerErrorCode: AccessDenied)
```

### Solution
1. Update the IAM role permissions for the CloudFormation service role
2. Log in to the AWS Management Console
3. Navigate to IAM > Roles
4. Find and select the role "github-actions-cloudformation-stack-role"
5. Add a new inline policy or modify an existing policy to include the following permissions:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "ec2:TerminateInstances"
            ],
            "Resource": "*"
        }
    ]
}
```

6. Save the policy changes
7. Re-run the GitHub Actions workflow to deploy the infrastructure
8. If the stack is still in a ROLLBACK_FAILED state, manually delete the stack using the AWS Management Console or AWS CLI before re-running the workflow

## Confidence Level
95% confidence in this analysis based on the clear error messages and stack events.
