### ISSUE TITLE
CloudFormation Deployment Failure: EC2 Instance Signal Timeout and IAM Role Permission Issues

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/CFNDeployment#46]
# CloudSmith Troubleshooting Summary
## Trigger details
| Workflow run  | Branch  | Commit  |
|---|---|---|
| [#15787719753](https://github.com/CloudSmith-Delivery-Troubleshooting/CFNDeployment/actions/runs/15787719753) |  ```ec2-timeout``` |  ```8adcbcdb0732f43025d6714d83152205088e36e8``` |
----
### Issue 1

**Problem**: The EC2Instance resource in the CloudFormation template has a CreationPolicy with a ResourceSignal timeout of only 10 seconds (PT10S), which is too short for the EC2 instance to initialize and send the required signal back to CloudFormation.

**File**: ```cloudformation-templates/infrastructure.yml```

**Error Log**:
```
2025-06-20T21:12:56.928000+00:00 | EC2Instance | AWS::EC2::Instance | Failed to receive 1 resource signal(s) within the specified duration
```

**Code snippet**:
```
EC2Instance:\n    Type: AWS::EC2::Instance\n    Properties:\n      InstanceType: t2.micro\n      SubnetId: !Ref PublicSubnetOne\n      SecurityGroupIds:\n        - !Ref ContainerSecurityGroup\n      ImageId: ami-0c55b159cbfafe1f0  # Amazon Linux 2 AMI (adjust for your region)\n      Tags:\n        - Key: Name\n          Value: !Sub "${EnvironmentName}-test-instance"\n    CreationPolicy:\n      ResourceSignal:\n        Timeout: PT10S
```

**Solution Plan**:

1. Modify the CloudFormation template to increase the ResourceSignal timeout value in the CreationPolicy section of the EC2Instance resource.
2. Open the file cloudformation-templates/infrastructure.yml
3. Locate the EC2Instance resource definition
4. Change the Timeout value from PT10S (10 seconds) to a more reasonable value like PT5M (5 minutes)
5. The modified code should look like:
                ```
                EC2Instance:
                  Type: AWS::EC2::Instance
                  Properties:
                    InstanceType: t2.micro
                    SubnetId: !Ref PublicSubnetOne
                    SecurityGroupIds:
                      - !Ref ContainerSecurityGroup
                    ImageId: ami-0c55b159cbfafe1f0  # Amazon Linux 2 AMI (adjust for your region)
                    Tags:
                      - Key: Name
                        Value: !Sub "${EnvironmentName}-test-instance"
                  CreationPolicy:
                    ResourceSignal:
                      Timeout: PT5M
                ```
6. Commit and push the changes to the repository
7. Re-run the GitHub Actions workflow

----

# CloudSmith Troubleshooting Summary
## Trigger details
| Workflow run  | Branch  | Commit  |
|---|---|---|
| [#15787719753](https://github.com/CloudSmith-Delivery-Troubleshooting/CFNDeployment/actions/runs/15787719753) |  ```ec2-timeout``` |  ```8adcbcdb0732f43025d6714d83152205088e36e8``` |
----
### Issue 2

**Problem**: The IAM role used for CloudFormation stack deployment (github-actions-cloudformation-stack-role) lacks the necessary ec2:TerminateInstances permission, which prevents the stack from being properly rolled back when the deployment fails.

**File**: ```N/A - IAM Role Configuration```

**Error Log**:
```
Resource handler returned message: "You are not authorized to perform this operation. User: arn:aws:sts::388276022184:assumed-role/github-actions-cloudformation-stack-role/AWSCloudFormation is not authorized to perform: ec2:TerminateInstances on resource: arn:aws:ec2:us-east-2:388276022184:instance/i-0f845ac99ac4ba304 because no identity-based policy allows the ec2:TerminateInstances action. (Service: Ec2, Status Code: 403, Request ID: 3fd0e032-a227-4377-8ccf-f21ead4dc832) (SDK Attempt Count: 1)" (RequestToken: 1207ed42-3c50-c1a7-92d0-f93e1d8b5d06, HandlerErrorCode: AccessDenied)
```

**Code snippet**:
```
N/A - IAM Role Configuration
```

**Solution Plan**:

1. Update the IAM role permissions for the CloudFormation service role
2. Log in to the AWS Management Console
3. Navigate to the IAM service
4. Find and select the role named "github-actions-cloudformation-stack-role"
5. Add a new inline policy or update an existing policy to include the ec2:TerminateInstances permission
6. The policy JSON should include:
                ```json
                {
                    "Version": "2012-10-17",
                    "Statement": [
                        {
                            "Effect": "Allow",
                            "Action": "ec2:TerminateInstances",
                            "Resource": "*"
                        }
                    ]
                }
                ```
7. Save the policy changes
8. Clean up the failed stack manually using the AWS CloudFormation console or CLI with appropriate permissions
9. Re-run the GitHub Actions workflow after fixing the EC2Instance timeout issue

----
