### ISSUE TITLE
CloudFormation Deployment Failure: EC2 Instance Creation Timeout and IAM Permission Issues

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/CFNDeployment#47]
# CloudSmith Troubleshooting Summary
## Trigger details
| Workflow run  | Branch  | Commit  |
|---|---|---|
| [#15787719753](https://github.com/CloudSmith-Delivery-Troubleshooting/CFNDeployment/actions/runs/15787719753) |  ```ec2-timeout``` |  ```8adcbcdb0732f43025d6714d83152205088e36e8``` |
----
### Issue 1

**Problem**: The EC2 instance creation failed because the CreationPolicy has an extremely short timeout of 10 seconds (PT10S) which is insufficient for the EC2 instance to initialize and send the required signal back to CloudFormation.

**File**: ```cloudformation-templates/infrastructure.yml```

**Error Log**:
```
2025-06-20T21:12:56.928000+00:00|  EC2Instance        |  AWS::EC2::Instance                         |  Failed to receive 1 resource signal(s) within the specified duration
```

**Code snippet**:
```
EC2Instance:\n    Type: AWS::EC2::Instance\n    Properties:\n      InstanceType: t2.micro\n      SubnetId: !Ref PublicSubnetOne\n      SecurityGroupIds:\n        - !Ref ContainerSecurityGroup\n      ImageId: ami-0c55b159cbfafe1f0  # Amazon Linux 2 AMI (adjust for your region)\n      Tags:\n        - Key: Name\n          Value: !Sub "${EnvironmentName}-test-instance"\n    CreationPolicy:\n      ResourceSignal:\n        Timeout: PT10S
```

**Solution Plan**:

1. Increase the CreationPolicy timeout to a more reasonable duration, such as 5 minutes (PT5M) or 10 minutes (PT10M), to allow sufficient time for the EC2 instance to initialize and send the required signal.
2. Modify the CloudFormation template at cloudformation-templates/infrastructure.yml by updating the CreationPolicy section:
                ```yaml
                EC2Instance:
                  Type: AWS::EC2::Instance
                  Properties:
                    InstanceType: t2.micro
                    SubnetId: !Ref PublicSubnetOne
                    SecurityGroupIds:
                      - !Ref ContainerSecurityGroup
                    ImageId: ami-0c55b159cbfafe1f0  # Amazon Linux 2 AMI (adjust for your region)
                    Tags:
                      - Key: Name
                        Value: !Sub "${EnvironmentName}-test-instance"
                  CreationPolicy:
                    ResourceSignal:
                      Timeout: PT5M
                ```
3. Additionally, ensure that the EC2 instance is properly configured to send the signal back to CloudFormation. This typically requires the cfn-signal helper script to be included in the instance's user data script.
4. If the EC2 instance needs to perform initialization tasks before signaling success, add a UserData script to the EC2 instance configuration:
                ```yaml
                UserData:
                  Fn::Base64: !Sub |
                    #!/bin/bash -xe
                    yum update -y
                    # Add any initialization commands here
                    
                    # Send signal back to CloudFormation
                    /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource EC2Instance --region ${AWS::Region}
                ```
5. Commit and push these changes to the repository to trigger a new deployment.

----

### Issue 2

**Problem**: The IAM role used for CloudFormation stack deployment (github-actions-cloudformation-stack-role) lacks the necessary permissions to terminate EC2 instances, which caused the stack rollback to fail.

**File**: ```.github/workflows/deploy.yml```

**Error Log**:
```
Resource handler returned message: "You are not authorized to perform this operation. User: arn:aws:sts::388276022184:assumed-role/github-actions-cloudformation-stack-role/AWSCloudFormation is not authorized to perform: ec2:TerminateInstances on resource: arn:aws:ec2:us-east-2:388276022184:instance/i-0f845ac99ac4ba304 because no identity-based policy allows the ec2:TerminateInstances action. (Service: Ec2, Status Code: 403, Request ID: 3fd0e032-a227-4377-8ccf-f21ead4dc832) (SDK Attempt Count: 1)" (RequestToken: 1207ed42-3c50-c1a7-92d0-f93e1d8b5d06, HandlerErrorCode: AccessDenied)
```

**Code snippet**:
```
- name: Deploy infrastructure with CloudFormation\n      id: infrastructure-stack\n      uses: aws-actions/aws-cloudformation-github-deploy@v1\n      with:\n        name: ${{ steps.env-name.outputs.environment }}-infra\n        template: cloudformation-templates/infrastructure.yml\n        role-arn: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-cloudformation-stack-role\n        no-fail-on-empty-changeset: "1"\n        parameter-overrides: >-\n          EnvironmentName=${{ steps.env-name.outputs.environment }},\n          VPC=${{ steps.vpc.outputs.vpc-id }},\n          PublicSubnetOne=${{ steps.vpc.outputs.subnet-one }},\n          PublicSubnetTwo=${{ steps.vpc.outputs.subnet-two }}
```

**Solution Plan**:

1. Update the IAM role permissions for the CloudFormation service role to include the necessary EC2 termination permissions.
2. Log in to the AWS Management Console and navigate to the IAM service.
3. Find the role named "github-actions-cloudformation-stack-role" and select it.
4. Add a new inline policy or update an existing policy to include the following permissions:
                ```json
                {
                    "Version": "2012-10-17",
                    "Statement": [
                        {
                            "Effect": "Allow",
                            "Action": [
                                "ec2:TerminateInstances",
                                "ec2:DeleteSecurityGroup",
                                "ec2:DescribeInstances",
                                "ec2:DescribeSecurityGroups"
                            ],
                            "Resource": "*"
                        }
                    ]
                }
                ```
5. Save the updated policy.
6. If the stack is still in a ROLLBACK_FAILED state, manually delete the stack using the AWS Management Console or AWS CLI before attempting a new deployment.
7. Run the following AWS CLI command to delete the stack:
                ```
                aws cloudformation delete-stack --stack-name CloudSmith-Delivery-Troubleshooting-CFNDeployment-infra
                ```
8. After the stack is deleted, trigger a new deployment by pushing changes to the repository.

----
