### ISSUE TITLE
CloudFormation deployment fails due to EC2 instance resource signal timeout

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/CFNDeployment#5]
## Root Cause Analysis

**Confidence Level:** 95%

#### Analysis
The EC2 instance creation is failing because the CloudFormation template specifies an extremely short timeout (10 seconds) for the EC2 instance to send a resource signal, but there is no user data script or mechanism configured to send this signal.

#### Impacted File
`cloudformation-templates/infrastructure.yml`

#### Code Snippet
```yaml
EC2Instance:
  Type: AWS::EC2::Instance
  Properties:
    InstanceType: t2.micro
    SubnetId: !Ref PublicSubnetOne
    SecurityGroupIds:
      - !Ref ContainerSecurityGroup
    ImageId: ami-0c55b159cbfafe1f0  # Amazon Linux 2 AMI (adjust for your region)
    Tags:
      - Key: Name
        Value: !Sub "${EnvironmentName}-test-instance"
  CreationPolicy:
    ResourceSignal:
      Timeout: PT10S
```

#### Error Log
```
2025-06-20T21:12:56.928000+00:00|  EC2Instance        |  AWS::EC2::Instance                         |  Failed to receive 1 resource signal(s) within the specified duration
```

#### Solution Plan
1. Either increase the ResourceSignal timeout to a more reasonable value (e.g., PT5M for 5 minutes) to allow the instance to fully initialize:
```yaml
EC2Instance:
  Type: AWS::EC2::Instance
  Properties:
    InstanceType: t2.micro
    SubnetId: !Ref PublicSubnetOne
    SecurityGroupIds:
      - !Ref ContainerSecurityGroup
    ImageId: ami-0c55b159cbfafe1f0  # Amazon Linux 2 AMI (adjust for your region)
    Tags:
      - Key: Name
        Value: !Sub "${EnvironmentName}-test-instance"
  CreationPolicy:
    ResourceSignal:
      Timeout: PT5M
```

2. Or add UserData to the EC2 instance to send the required signal:
```yaml
EC2Instance:
  Type: AWS::EC2::Instance
  Properties:
    InstanceType: t2.micro
    SubnetId: !Ref PublicSubnetOne
    SecurityGroupIds:
      - !Ref ContainerSecurityGroup
    ImageId: ami-0c55b159cbfafe1f0  # Amazon Linux 2 AMI (adjust for your region)
    Tags:
      - Key: Name
        Value: !Sub "${EnvironmentName}-test-instance"
    UserData:
      Fn::Base64: !Sub |
        #!/bin/bash -xe
        yum update -y
        yum install -y aws-cfn-bootstrap
        /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource EC2Instance --region ${AWS::Region}
  CreationPolicy:
    ResourceSignal:
      Timeout: PT5M
```

3. Or remove the CreationPolicy entirely if the signal is not needed:
```yaml
EC2Instance:
  Type: AWS::EC2::Instance
  Properties:
    InstanceType: t2.micro
    SubnetId: !Ref PublicSubnetOne
    SecurityGroupIds:
      - !Ref ContainerSecurityGroup
    ImageId: ami-0c55b159cbfafe1f0  # Amazon Linux 2 AMI (adjust for your region)
    Tags:
      - Key: Name
        Value: !Sub "${EnvironmentName}-test-instance"
```

#### Analysis
The AMI ID (ami-0c55b159cbfafe1f0) specified in the CloudFormation template may not be available in the us-east-2 region or may have been deprecated.

#### Impacted File
`cloudformation-templates/infrastructure.yml`

#### Code Snippet
```yaml
EC2Instance:
  Type: AWS::EC2::Instance
  Properties:
    InstanceType: t2.micro
    SubnetId: !Ref PublicSubnetOne
    SecurityGroupIds:
      - !Ref ContainerSecurityGroup
    ImageId: ami-0c55b159cbfafe1f0  # Amazon Linux 2 AMI (adjust for your region)
    Tags:
      - Key: Name
        Value: !Sub "${EnvironmentName}-test-instance"
```

#### Error Log
```
2025-06-20T21:12:56.928000+00:00|  EC2Instance        |  AWS::EC2::Instance                         |  Failed to receive 1 resource signal(s) within the specified duration
```

#### Solution Plan
1. Update the AMI ID to a valid, current Amazon Linux 2 AMI for the us-east-2 region:
```yaml
EC2Instance:
  Type: AWS::EC2::Instance
  Properties:
    InstanceType: t2.micro
    SubnetId: !Ref PublicSubnetOne
    SecurityGroupIds:
      - !Ref ContainerSecurityGroup
    ImageId: ami-0a606d8395a538502  # Updated Amazon Linux 2 AMI for us-east-2
    Tags:
      - Key: Name
        Value: !Sub "${EnvironmentName}-test-instance"
```

2. Or better yet, use the AWS Systems Manager Parameter Store to dynamically retrieve the latest Amazon Linux 2 AMI:
```yaml
EC2Instance:
  Type: AWS::EC2::Instance
  Properties:
    InstanceType: t2.micro
    SubnetId: !Ref PublicSubnetOne
    SecurityGroupIds:
      - !Ref ContainerSecurityGroup
    ImageId: !SSM:/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
    Tags:
      - Key: Name
        Value: !Sub "${EnvironmentName}-test-instance"
```
