### ISSUE TITLE
CloudFormation deployment failing due to EC2 instance CreationPolicy timeout

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/CFNDeployment#50]
# CloudSmith Troubleshooting Summary
## Trigger details
| Workflow run  | Branch  | Commit  |
|---|---|---|
| [#15782168281](https://github.com/CloudSmith-Delivery-Troubleshooting/CFNDeployment/actions/runs/15782168281) |  ```ec2-timeout``` |  ```723b4935efb72ada24f67e14267a0756a7fda064``` |
----
### Issue 1

**Problem**: The CloudFormation deployment is failing because the EC2Instance resource has an extremely short CreationPolicy timeout of only 10 seconds (PT10S), which is insufficient for an EC2 instance to initialize and send a success signal. This causes the CloudFormation stack to wait for the signal, timeout after 10 seconds, and then roll back, resulting in the workflow being cancelled.

**File**: ```cloudformation-templates/infrastructure.yml```

**Error Log**:
```
2025-06-20T21:00:14.1328696Z ##[error]The operation was canceled.
```

**Code snippet**:
```
EC2Instance:\n    Type: AWS::EC2::Instance\n    Properties:\n      InstanceType: t2.micro\n      SubnetId: !Ref PublicSubnetOne\n      SecurityGroupIds:\n        - !Ref ContainerSecurityGroup\n      ImageId: ami-0c55b159cbfafe1f0  # Amazon Linux 2 AMI (adjust for your region)\n      Tags:\n        - Key: Name\n          Value: !Sub "${EnvironmentName}-test-instance"\n    CreationPolicy:\n      ResourceSignal:\n        Timeout: PT10S
```

**Solution Plan**:

1. Increase the CreationPolicy timeout to a more reasonable value to allow the EC2 instance enough time to initialize and send a success signal. A typical EC2 instance needs at least 5-15 minutes to fully initialize.
2. Modify the CloudFormation template at `cloudformation-templates/infrastructure.yml` by changing the timeout value from PT10S (10 seconds) to PT15M (15 minutes):
```yaml
                EC2Instance:
                  Type: AWS::EC2::Instance
                  Properties:
                    InstanceType: t2.micro
                    SubnetId: !Ref PublicSubnetOne
                    SecurityGroupIds:
                      - !Ref ContainerSecurityGroup
                    ImageId: ami-0c55b159cbfafe1f0  # Amazon Linux 2 AMI (adjust for your region)
                    Tags:
                      - Key: Name
                        Value: !Sub "${EnvironmentName}-test-instance"
                  CreationPolicy:
                    ResourceSignal:
                      Timeout: PT15M
```
3. If you don't actually need the EC2 instance to send a signal, you can remove the CreationPolicy entirely. This would be appropriate if you're not using cfn-signal in your EC2 instance's user data.
4. If you do need the signal, ensure that your EC2 instance's user data script includes the necessary code to send a signal to CloudFormation using the cfn-signal helper script.
5. Commit and push the changes to the ec2-timeout branch:
```
                git add cloudformation-templates/infrastructure.yml
                git commit -m "Fix: Increase EC2 instance CreationPolicy timeout"
                git push origin ec2-timeout
```
6. Re-run the GitHub Actions workflow to deploy the infrastructure with the updated timeout value.

----

# CloudSmith Troubleshooting Summary
## Trigger details
| Workflow run  | Branch  | Commit  |
|---|---|---|
| [#15782168281](https://github.com/CloudSmith-Delivery-Troubleshooting/CFNDeployment/actions/runs/15782168281) |  ```ec2-timeout``` |  ```723b4935efb72ada24f67e14267a0756a7fda064``` |
----
### Issue 2

**Problem**: There's a mismatch between the ECR repository name in the CloudFormation template and the repository name used in the GitHub Actions workflow. The CloudFormation template was updated to use 'ecsimage' as the repository name, but the GitHub Actions workflow still references 'reponame', which would cause the second job to fail when trying to push to the ECR repository.

**File**: ```.github/workflows/deploy.yml```

**Error Log**:
```
The repository name was changed from "reponame" to "ecsimage" in the CloudFormation template, but the workflow still uses "reponame".
```

**Code snippet**:
```
- name: Build, tag, and push webapp image\n      id: build-image\n      env:\n        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}\n        ECR_REPOSITORY: reponame\n        IMAGE_TAG: webapp-${{ github.sha }}\n      run: |\n        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .\n        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG\n        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> "$GITHUB_OUTPUT"
```

**Solution Plan**:

1. Update the GitHub Actions workflow file to use the same ECR repository name as defined in the CloudFormation template.
2. Modify the `.github/workflows/deploy.yml` file to change the ECR_REPOSITORY value from 'reponame' to 'ecsimage':
```yaml
                - name: Build, tag, and push webapp image
                  id: build-image
                  env:
                    ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                    ECR_REPOSITORY: ecsimage
                    IMAGE_TAG: webapp-${{ github.sha }}
                  run: |
                    docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
                    docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
                    echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> "$GITHUB_OUTPUT"
```
3. Commit and push the changes to the ec2-timeout branch:
```
                git add .github/workflows/deploy.yml
                git commit -m "Fix: Update ECR repository name in workflow to match CloudFormation template"
                git push origin ec2-timeout
```
4. This change should be made after fixing the EC2 instance timeout issue, as that is the primary cause of the current workflow failure.

----
