### ISSUE TITLE
Fix ECR Repository Name Pattern Validation Error in CloudFormation Template

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/CFNDeployment#53]
# CloudSmith Troubleshooting Summary
## Trigger details
| Workflow run  | Branch  | Commit  |
|---|---|---|
| [#15796596671](https://github.com/CloudSmith-Delivery-Troubleshooting/CFNDeployment/actions/runs/15796596671) |  ```template-validation``` |  ```3e84dd7e124acc9c7d78168239049e3c34648fd0``` |
----
### Issue 1

**Problem**: The CloudFormation deployment failed because the ECR repository name "repositoryName" does not meet AWS ECR repository naming requirements. AWS ECR repository names must follow a specific pattern, which typically includes allowing only letters, numbers, hyphens, underscores, and periods, and must start with a letter.

**File**: ```cloudformation-templates/infrastructure.yml```

**Error Log**:
```
Resource handler returned message: "Model validation failed (#/RepositoryName: failed validation constraint for keyword [pattern])" (RequestToken: d8473b46-45b2-3e7f-e5e3-bc31f23c332e, HandlerErrorCode: InvalidRequest)
```

**Code snippet**:
```
# ECR Repository\n  ImageRepository:\n    Type: AWS::ECR::Repository\n    Properties:\n      RepositoryName: repositoryName
```

**Solution Plan**:

1. Update the ECR repository name in the CloudFormation template to follow AWS ECR naming requirements.
2. Open the file: cloudformation-templates/infrastructure.yml
3. Modify the ImageRepository resource to use a valid repository name format.
4. Replace the generic "repositoryName" with a specific name that follows the pattern, preferably using the environment name as a prefix.  The corrected code should look like:
```yaml
                # ECR Repository
                ImageRepository:
                  Type: AWS::ECR::Repository
                  Properties:
                    RepositoryName: !Sub ${EnvironmentName}-webapp-repository
```
5. Commit the changes to the repository
6. Re-run the GitHub workflow to deploy the infrastructure

----
