### ISSUE TITLE
CloudFormation deployment fails due to insufficient EC2 instance creation timeout

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/CFNDeployment#54]
# CloudSmith Troubleshooting Summary
## Trigger details
| Workflow run  | Branch  | Commit  |
|---|---|---|
| [#15782168281](https://github.com/CloudSmith-Delivery-Troubleshooting/CFNDeployment/actions/runs/15782168281) |  ```ec2-timeout``` |  ```723b4935efb72ada24f67e14267a0756a7fda064``` |
----
### Issue 1

**Problem**: The CloudFormation deployment is failing because the EC2Instance resource in the infrastructure.yml template has an extremely short CreationPolicy timeout of 10 seconds (PT10S), which is insufficient for the EC2 instance to initialize and signal completion.

**File**: ```cloudformation-templates/infrastructure.yml```

**Error Log**:
```
2025-06-20T21:00:14.1328696Z ##[error]The operation was canceled.\n2025-06-20T21:00:14.1420746Z Post job cleanup.
```

**Code snippet**:
```
EC2Instance:\n    Type: AWS::EC2::Instance\n    Properties:\n      InstanceType: t2.micro\n      SubnetId: !Ref PublicSubnetOne\n      SecurityGroupIds:\n        - !Ref ContainerSecurityGroup\n      ImageId: ami-0c55b159cbfafe1f0  # Amazon Linux 2 AMI (adjust for your region)\n      Tags:\n        - Key: Name\n          Value: !Sub "${EnvironmentName}-test-instance"\n    CreationPolicy:\n      ResourceSignal:\n        Timeout: PT10S
```

**Solution Plan**:

1. Increase the CreationPolicy timeout value in the infrastructure.yml template to allow sufficient time for the EC2 instance to initialize and signal completion.
2. Modify the EC2Instance resource in the CloudFormation template as follows:
```yaml
                EC2Instance:
                  Type: AWS::EC2::Instance
                  Properties:
                    InstanceType: t2.micro
                    SubnetId: !Ref PublicSubnetOne
                    SecurityGroupIds:
                      - !Ref ContainerSecurityGroup
                    ImageId: ami-0c55b159cbfafe1f0  # Amazon Linux 2 AMI (adjust for your region)
                    Tags:
                      - Key: Name
                        Value: !Sub "${EnvironmentName}-test-instance"
                  CreationPolicy:
                    ResourceSignal:
                      Timeout: PT15M
```
3. The PT15M value sets the timeout to 15 minutes, which is a more reasonable duration for an EC2 instance to initialize and signal completion.
4. Commit and push the changes to the repository.
5. Re-run the GitHub workflow to deploy the infrastructure.
6. Monitor the CloudFormation stack creation to ensure it completes successfully.

----
