### ISSUE TITLE
CloudFormation Deployment Failure: Log Group Resource Conflict and ECR Repository Name Mismatch

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/CFNDeployment#55]
# CloudSmith Troubleshooting Summary
## Trigger details
| Workflow run  | Branch  | Commit  |
|---|---|---|
| [#15796736735](https://github.com/CloudSmith-Delivery-Troubleshooting/CFNDeployment/actions/runs/15796736735) |  ```resource-conflict``` |  ```e775e6ca9b13dc14b31775ddda2fe206b5d95941``` |
----
### Issue 1

**Problem**: The CloudFormation deployment failed because the AWS::Logs::LogGroup resource named "cfndeployment-log-group" already exists in the AWS account. This is causing the entire stack to roll back.

**File**: ```cloudformation-templates/infrastructure.yml```

**Error Log**:
```
Resource handler returned message: "Resource of type \'AWS::Logs::LogGroup\' with identifier \'{"/properties/LogGroupName":"cfndeployment-log-group"}\' already exists." (RequestToken: 34d4fe5b-3fc0-5ef1-a357-48740bb4c641, HandlerErrorCode: AlreadyExists)
```

**Code snippet**:
```
AppLogGroup:\n    Type: AWS::Logs::LogGroup\n    Properties:\n      LogGroupName: "cfndeployment-log-group"\n      RetentionInDays: 14
```

**Solution Plan**:

1. Modify the CloudFormation template to use a unique LogGroupName or use a dynamic name that includes the environment name to avoid conflicts:
```yaml
                   AppLogGroup:
                     Type: AWS::Logs::LogGroup
                     Properties:
                       LogGroupName: !Sub "${EnvironmentName}-cfndeployment-log-group"
                       RetentionInDays: 14
```
2. Alternatively, add a DeletionPolicy attribute to the LogGroup resource to retain it between deployments:
```yaml
                   AppLogGroup:
                     Type: AWS::Logs::LogGroup
                     DeletionPolicy: Retain
                     Properties:
                       LogGroupName: "cfndeployment-log-group"
                       RetentionInDays: 14
```
3. If you need to keep the same log group name, you can manually delete the existing log group before deployment:
```bash
                   aws logs delete-log-group --log-group-name cfndeployment-log-group
```
4. Commit the changes to the infrastructure.yml file and push to trigger a new deployment.

----

# CloudSmith Troubleshooting Summary
## Trigger details
| Workflow run  | Branch  | Commit  |
|---|---|---|
| [#15796736735](https://github.com/CloudSmith-Delivery-Troubleshooting/CFNDeployment/actions/runs/15796736735) |  ```resource-conflict``` |  ```e775e6ca9b13dc14b31775ddda2fe206b5d95941``` |
----
### Issue 2

**Problem**: There is a resource name conflict in the deployment workflow. The ECR repository name "reponame" is referenced in the deploy-web-app job, but the repository defined in the CloudFormation template is named "reponame2".

**File**: ```.github/workflows/deploy.yml```

**Error Log**:
```
The deploy-web-app job was skipped because the deploy-infrastructure job failed. The ECR repository name mismatch would have caused an error in the second job if the first job had succeeded.
```

**Code snippet**:
```
- name: Build, tag, and push webapp image\n      id: build-image\n      env:\n        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}\n        ECR_REPOSITORY: reponame\n        IMAGE_TAG: webapp-${{ github.sha }}\n      run: |\n        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .\n        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG\n        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> "$GITHUB_OUTPUT"
```

**Solution Plan**:

1. Update the ECR_REPOSITORY environment variable in the deploy.yml workflow file to match the repository name defined in the CloudFormation template:
```yaml
                   - name: Build, tag, and push webapp image
                     id: build-image
                     env:
                       ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                       ECR_REPOSITORY: reponame2
                       IMAGE_TAG: webapp-${{ github.sha }}
                     run: |
                       docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
                       docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
                       echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> "$GITHUB_OUTPUT"
```
2. Alternatively, update the repository name in the CloudFormation template to match the one used in the workflow:
```yaml
                   ImageRepository:
                     Type: AWS::ECR::Repository
                     Properties:
                       RepositoryName: reponame
```
3. Commit the changes and push to trigger a new deployment.

----

# CloudSmith Troubleshooting Summary
## Trigger details
| Workflow run  | Branch  | Commit  |
|---|---|---|
| [#15796736735](https://github.com/CloudSmith-Delivery-Troubleshooting/CFNDeployment/actions/runs/15796736735) |  ```resource-conflict``` |  ```e775e6ca9b13dc14b31775ddda2fe206b5d95941``` |
----
### Issue 3

**Problem**: The recent commit removed the "ImageRepository2" resource from the CloudFormation template, which previously had the repository name "reponame" that matches what\'s used in the workflow file. This change is directly related to the repository name mismatch issue.

**File**: ```cloudformation-templates/infrastructure.yml```

**Error Log**:
```
From the failed commits information: \ndiff\n@@ -27,11 +27,6 @@ Resources:\n     Properties:\n       RepositoryName: reponame2\n \n-  ImageRepository2:\n-    Type: AWS::ECR::Repository\n-    Properties:\n-      RepositoryName: reponame\n-
```

**Code snippet**:
```
-  ImageRepository2:\n-    Type: AWS::ECR::Repository\n-    Properties:\n-      RepositoryName: reponame\n-
```

**Solution Plan**:

1. Restore the removed ImageRepository2 resource in the CloudFormation template:
```yaml
                   ImageRepository2:
                     Type: AWS::ECR::Repository
                     Properties:
                       RepositoryName: reponame
```
2. Alternatively, update the ECR_REPOSITORY environment variable in the deploy.yml workflow file to use "reponame2" as suggested in the previous finding.
3. Ensure that the repository names are consistent across all files to prevent future conflicts.
4. Commit the changes and push to trigger a new deployment.

----
