### ISSUE TITLE
CloudFormation Stack in ROLLBACK_FAILED State Due to Hardcoded ECR Repository Name

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/CFNDeployment#6]
## Root Cause Analysis

**Confidence Level**: 95%

### Problem

The CloudFormation stack is in a ROLLBACK_FAILED state, which prevents any updates to the stack. This is likely due to the ECR repository resource having a hardcoded name "repositoryName" that either already exists or had a previous failed deployment that couldn't be rolled back properly.

### Impacted File
`cloudformation-templates/infrastructure.yml`

### Problematic Code
```yaml
# ECR Repository
ImageRepository:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: repositoryName
```

### Error Log
```
##[error]Stack:arn:aws:cloudformation:us-east-2:***:stack/CloudSmith-Delivery-Troubleshooting-CFNDeployment-infra/45982dd0-4e1b-11f0-9cff-02499d1c9c23 is in ROLLBACK_FAILED state and can not be updated.
```

## Solution Plan

1. Delete the failed CloudFormation stack manually using the AWS Management Console or AWS CLI:
   ```
   aws cloudformation delete-stack --stack-name CloudSmith-Delivery-Troubleshooting-CFNDeployment-infra
   ```

2. Modify the ECR repository name in the CloudFormation template to use a dynamic name based on the environment to avoid naming conflicts:
   ```yaml
   # ECR Repository
   ImageRepository:
     Type: AWS::ECR::Repository
     Properties:
       RepositoryName: !Sub ${EnvironmentName}-repo
   ```

3. Add the `disable-rollback: 1` parameter to the CloudFormation deployment step in the GitHub workflow to prevent rollback failures in the future:
   ```yaml
   - name: Deploy infrastructure with CloudFormation
     id: infrastructure-stack
     uses: aws-actions/aws-cloudformation-github-deploy@v1
     with:
       name: ${{ steps.env-name.outputs.environment }}-infra
       template: cloudformation-templates/infrastructure.yml
       role-arn: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-cloudformation-stack-role
       no-fail-on-empty-changeset: "1"
       disable-rollback: "1"
       parameter-overrides: >-
         EnvironmentName=${{ steps.env-name.outputs.environment }},
         VPC=${{ steps.vpc.outputs.vpc-id }},
         PublicSubnetOne=${{ steps.vpc.outputs.subnet-one }},
         PublicSubnetTwo=${{ steps.vpc.outputs.subnet-two }}
   ```

4. Run the workflow again after these changes to create a new stack.
