### ISSUE TITLE
CloudFormation Deployment Failure: Invalid ECR Repository Name Pattern

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/CFNDeployment#7]
## Root Cause Analysis

The CloudFormation stack deployment is failing because the ECR repository name "repositoryName" in the infrastructure template does not meet AWS ECR repository naming requirements. ECR repository names must follow a specific pattern, typically allowing lowercase letters, numbers, hyphens, and underscores, but the literal string "repositoryName" was used instead of a valid name or a dynamic reference.

### Confidence Level
95%

### Impacted File
`cloudformation-templates/infrastructure.yml`

### Problematic Code
```yaml
# ECR Repository
ImageRepository:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: repositoryName
```

### Error Log
```
Resource handler returned message: "Model validation failed (#/RepositoryName: failed validation constraint for keyword [pattern])" (RequestToken: d8473b46-45b2-3e7f-e5e3-bc31f23c332e, HandlerErrorCode: InvalidRequest)
```

## Solution Plan

1. Update the ECR repository name in the CloudFormation template to use a valid name that follows AWS naming patterns
2. Use a dynamic reference to the environment name to ensure uniqueness
3. Ensure the repository name matches what's used in the workflow file
4. Replace the hardcoded "repositoryName" with a reference to the environment name

### Corrected Code for CloudFormation Template
```yaml
# ECR Repository
ImageRepository:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: !Sub ${EnvironmentName}-repo
```

### Update to Workflow File
Also update the workflow file to use the same repository name:
```yaml
- name: Build, tag, and push webapp image
  id: build-image
  env:
    ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
    ECR_REPOSITORY: ${{ needs.deploy-infrastructure.outputs.env-name }}-repo
    IMAGE_TAG: webapp-${{ github.sha }}
```

This will ensure that the ECR repository name follows AWS naming requirements and maintains consistency between the CloudFormation template and the workflow file.
