### ISSUE TITLE
CloudFormation Stack Deployment Failure: Stack in DELETE_IN_PROGRESS State

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/CFNDeployment#9]
## Root Cause Analysis

**Confidence Level:** 95%

### Problem Description
The CloudFormation stack deployment is failing because it's attempting to update a stack that is currently in the DELETE_IN_PROGRESS state. The workflow is trying to deploy infrastructure using the CloudFormation template, but the stack with the same name is already being deleted, causing a resource conflict.

### Impacted File
`.github/workflows/deploy.yml`

### Error Log
```
##[error]Stack:arn:aws:cloudformation:us-east-2:***:stack/CloudSmith-Delivery-Troubleshooting-CFNDeployment-infra-02/11b2e1d0-4ead-11f0-9b72-026e035381ef is in DELETE_IN_PROGRESS state and can not be updated.
```

### Problematic Code
```yaml
- name: Deploy infrastructure with CloudFormation
  id: infrastructure-stack
  uses: aws-actions/aws-cloudformation-github-deploy@v1
  with:
    name: ${{ steps.env-name.outputs.environment }}-infra-02
    template: cloudformation-templates/infrastructure.yml
    role-arn: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-cloudformation-stack-role
    no-fail-on-empty-changeset: "1"
    parameter-overrides: >-
      EnvironmentName=${{ steps.env-name.outputs.environment }},
      VPC=${{ steps.vpc.outputs.vpc-id }},
      PublicSubnetOne=${{ steps.vpc.outputs.subnet-one }},
      PublicSubnetTwo=${{ steps.vpc.outputs.subnet-two }}
```

## Solution Plan

1. Modify the workflow to check if the stack exists and its current state before attempting deployment
2. Add a wait mechanism to ensure the stack deletion is complete before attempting to create a new stack
3. Implement a unique stack naming strategy to avoid conflicts with stacks that might be in the process of deletion

### Proposed Changes

Add a step to check the stack status before deployment:

```yaml
- name: Check if stack exists and its status
  id: check-stack
  run: |
    STACK_NAME="${{ steps.env-name.outputs.environment }}-infra-02"
    echo "Checking if stack $STACK_NAME exists..."
    
    # Check if stack exists and get its status
    STACK_STATUS=$(aws cloudformation describe-stacks --stack-name "$STACK_NAME" --query "Stacks[0].StackStatus" --output text 2>/dev/null || echo "STACK_NOT_FOUND")
    echo "Stack status: $STACK_STATUS"
    
    # If stack is being deleted, wait for deletion to complete
    if [[ "$STACK_STATUS" == *DELETE_IN_PROGRESS* ]]; then
      echo "Stack is being deleted. Waiting for deletion to complete..."
      aws cloudformation wait stack-delete-complete --stack-name "$STACK_NAME"
      echo "Stack deletion completed"
    fi
    
    # Set output for next steps
    if [[ "$STACK_STATUS" == "STACK_NOT_FOUND" ]]; then
      echo "stack_exists=false" >> "$GITHUB_OUTPUT"
    else
      echo "stack_exists=true" >> "$GITHUB_OUTPUT"
      echo "stack_status=$STACK_STATUS" >> "$GITHUB_OUTPUT"
    fi
```

Keep the existing deployment step after the check:

```yaml
- name: Deploy infrastructure with CloudFormation
  id: infrastructure-stack
  uses: aws-actions/aws-cloudformation-github-deploy@v1
  with:
    name: ${{ steps.env-name.outputs.environment }}-infra-02
    template: cloudformation-templates/infrastructure.yml
    role-arn: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-cloudformation-stack-role
    no-fail-on-empty-changeset: "1"
    parameter-overrides: >-
      EnvironmentName=${{ steps.env-name.outputs.environment }},
      VPC=${{ steps.vpc.outputs.vpc-id }},
      PublicSubnetOne=${{ steps.vpc.outputs.subnet-one }},
      PublicSubnetTwo=${{ steps.vpc.outputs.subnet-two }}
```
